name: Add comment on review request

on:
  issue_comment:
    types: [created]

jobs:
  add_comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: review
        run: |
          RESULT=$(bash curl.sh)
          echo RESULT=$RESULT >> $GITHUB_ENV
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ISSUE_BODY: ${{ github.event.issue.body }}
      - name: Add comment
        run: |
          gh issue comment "$NUMBER" --repo "$REPO" --body "$RESULT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
