name: Add comment on review request

on:
  issue_comment:
    types: [created]

jobs:
  add_comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get Issue comment
        run: |
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "ISSUE_BODY=$ISSUE_BODY" >> $GITHUB_ENV
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
      - name: Add comment
        run: gh issue comment "$NUMBER" --repo "$REPO" --body "$ISSUE_BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
