name: Add comment on review request

on:
  issue_comment:
    types: [created]

jobs:
  add_comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: get issue body and set output
        uses: actions/github-script@v6
        id: set-result
        with:
          script: |
            echo "Issue Body: ${{ github.event.issue.body }}"
            core.setOutput(issue-body, value)
      - name: Add comment
        run: gh issue comment "$NUMBER" --repo "$REPO" --body "${{steps.set-result.outputs.issue-body}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
